backend:
  name: github
  repo: eduplessis/plp-nuxt # Change to your repo

media_folder: "static/uploads" # Folder where user uploaded files should go
public_folder: "/uploads"

collections: # A list of collections the CMS should be able to edit
  - name: "projets" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Projet" # Used in the UI, ie.: "New Post"
    folder: "content/projets"
    slug: "{{year}}-{{slug}}"
    format: 'json'
    create: true # Allow users to create new documents in this collection
    fields: # The fields each document in this collection have
      - {label: "Titre", name: "title", widget: "string", tagname: "h1"}
      - {label: "Date du Projet", name: "date", widget: "datetime", format: "YYYY-MM-DD"}
      - {label: "Type de Projet", name: "type", widget: "select", options: ["residentiel", "commercial", "scolaire"]}
      - {label: "Cover Image", name: "image", widget: "image", required: true, tagname: ""}
      - {label: "Body", name: "body", widget: "markdown"}
      - label: "Gallery"
        name: "gallery"
        widget: "list"
        required: false
        fields:
          - {label: Image, name: images, widget: image}
    meta:
      - {label: "SEO Description", name: "description", widget: "text"}
